// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzKSXpHFu50mw5-VX56fpRWFIHK8gl3-w',
    appId: '1:159314935593:web:9687d20ca5be605ce60138',
    messagingSenderId: '159314935593',
    projectId: 'chopdirect-bbdb5',
    authDomain: 'chopdirect-bbdb5.firebaseapp.com',
    storageBucket: 'chopdirect-bbdb5.firebasestorage.app',
    measurementId: 'G-EVSP5GXFGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAELjbXchy9VBwO6yruxTlBs2S-2nHEJRc',
    appId: '1:159314935593:android:e0f7e140437edfb4e60138',
    messagingSenderId: '159314935593',
    projectId: 'chopdirect-bbdb5',
    storageBucket: 'chopdirect-bbdb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxPfGJ-9PDzDbuJXsvrFa3fWJqJn5EvMU',
    appId: '1:159314935593:ios:25894ada948f635de60138',
    messagingSenderId: '159314935593',
    projectId: 'chopdirect-bbdb5',
    storageBucket: 'chopdirect-bbdb5.firebasestorage.app',
    iosClientId: '159314935593-o0gmmp49laf265u602it1r5o1ig43f6o.apps.googleusercontent.com',
    iosBundleId: 'com.example.chopdirect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxPfGJ-9PDzDbuJXsvrFa3fWJqJn5EvMU',
    appId: '1:159314935593:ios:25894ada948f635de60138',
    messagingSenderId: '159314935593',
    projectId: 'chopdirect-bbdb5',
    storageBucket: 'chopdirect-bbdb5.firebasestorage.app',
    iosClientId: '159314935593-o0gmmp49laf265u602it1r5o1ig43f6o.apps.googleusercontent.com',
    iosBundleId: 'com.example.chopdirect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzKSXpHFu50mw5-VX56fpRWFIHK8gl3-w',
    appId: '1:159314935593:web:a517508a52b07a82e60138',
    messagingSenderId: '159314935593',
    projectId: 'chopdirect-bbdb5',
    authDomain: 'chopdirect-bbdb5.firebaseapp.com',
    storageBucket: 'chopdirect-bbdb5.firebasestorage.app',
    measurementId: 'G-GK53LFEBSE',
  );
}
